from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

class BoundingBoxSchema(BaseModel):
    """Pydantic model representing absolute pixel coordinate bounding box annotations."""
    x: int = Field(..., description="Top-left corner X-coordinate in pixels.")
    y: int = Field(..., description="Top-left corner Y-coordinate in pixels.")
    width: int = Field(..., description="Box width in pixels.")
    height: int = Field(..., description="Box height in pixels.")

class PredictResponse(BaseModel):
    """API JSON response schema returned by the POST /predict endpoint."""
    prediction: str = Field(..., description="Prediction status ('Tampered' or 'Authentic').")
    confidence: float = Field(..., description="Inference confidence score (0-100%).")
    forgery_type: str = Field(..., description="Identified forgery category (e.g. Splicing, Copy-Move).")
    bounding_boxes: List[BoundingBoxSchema] = Field(..., description="List of bounding boxes enclosing forged areas.")
    reasoning: str = Field(..., description="Natural language reasoning explanation generated by the VLM.")
    latency_ms: int = Field(..., description="Inference execution latency in milliseconds.")

    # Backward compatibility fields for frontend UI
    tampered: bool = Field(..., description="True if document forgery or tampering was detected.")
    explanation: str = Field(..., description="Natural language reasoning explanation generated by the VLM.")
    processing_time_ms: int = Field(..., description="Inference execution latency in milliseconds.")

class HealthResponse(BaseModel):
    """System health check status endpoint schema."""
    status: str = Field("ok", description="Status code ('ok' or 'error').")
    device: str = Field(..., description="Active device backend.")
    gpu_memory_usage: str = Field(..., description="Formatted string of GPU allocation limits.")

class ModelInfoResponse(BaseModel):
    """Base model VLM metadata config properties schema."""
    model_name: str = Field(..., description="Base Vision-Language Model loaded.")
    lora_rank: int = Field(..., description="PEFT adapter Rank parameter (r).")
    lora_alpha: int = Field(..., description="LoRA scaling multiplier (lora_alpha).")
    precision: str = Field(..., description="Tensors precision (e.g. float32, float16).")
    trainable_parameters: int = Field(..., description="Number of active adapter weights.")
    frozen_parameters: int = Field(..., description="Number of frozen backbone base weights.")

class MetricsResponse(BaseModel):
    """Real-time performance profiling counts metrics schema."""
    total_requests: int = Field(0, description="Total API predict queries count.")
    successful_requests: int = Field(0, description="Successful model evaluations count.")
    failed_requests: int = Field(0, description="Failed predictions count (exception crashed).")
    avg_inference_time_ms: float = Field(0.0, description="Running average prediction latency in milliseconds.")
    model_loading_time_ms: float = Field(..., description="Initial VLM startup reload overhead in milliseconds.")

class VersionResponse(BaseModel):
    """API version manifest details schema."""
    version: str = Field("1.0.0", description="SemVer identifier.")
    project: str = Field("DocForge", description="Project name.")
    phase: str = Field("Phase 5: Deployment System", description="Implementation milestones phase.")
